package com.mybatis.generator.entity.test;

import java.util.Date;

/**
 * Database Table Remarks:
 *   附件表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_attachment
 */
public class SysAttachment {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   业务表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.form_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long formId;

    /**
     * Database Column Remarks:
     *   附件名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.attach_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String attachName;

    /**
     * Database Column Remarks:
     *   业务表名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.table_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String tableName;

    /**
     * Database Column Remarks:
     *   附件地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.url
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String url;

    /**
     * Database Column Remarks:
     *   附件大小
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.file_size
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long fileSize;

    /**
     * Database Column Remarks:
     *   存储类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.storage_type
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String storageType;

    /**
     * Database Column Remarks:
     *   序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer sequenceNo;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   更新用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long updatedBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date creationDate;

    /**
     * Database Column Remarks:
     *   创建用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long createdBy;

    /**
     * Database Column Remarks:
     *   版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer version;

    /**
     * Database Column Remarks:
     *   附件内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.content
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private byte[] content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.id
     *
     * @return the value of sys_attachment.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.id
     *
     * @param id the value for sys_attachment.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.form_id
     *
     * @return the value of sys_attachment.form_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.form_id
     *
     * @param formId the value for sys_attachment.form_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setFormId(Long formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.attach_name
     *
     * @return the value of sys_attachment.attach_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getAttachName() {
        return attachName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.attach_name
     *
     * @param attachName the value for sys_attachment.attach_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setAttachName(String attachName) {
        this.attachName = attachName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.table_name
     *
     * @return the value of sys_attachment.table_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.table_name
     *
     * @param tableName the value for sys_attachment.table_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.url
     *
     * @return the value of sys_attachment.url
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.url
     *
     * @param url the value for sys_attachment.url
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.file_size
     *
     * @return the value of sys_attachment.file_size
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.file_size
     *
     * @param fileSize the value for sys_attachment.file_size
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.storage_type
     *
     * @return the value of sys_attachment.storage_type
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getStorageType() {
        return storageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.storage_type
     *
     * @param storageType the value for sys_attachment.storage_type
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setStorageType(String storageType) {
        this.storageType = storageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.sequence_no
     *
     * @return the value of sys_attachment.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getSequenceNo() {
        return sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.sequence_no
     *
     * @param sequenceNo the value for sys_attachment.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.update_date
     *
     * @return the value of sys_attachment.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.update_date
     *
     * @param updateDate the value for sys_attachment.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.updated_by
     *
     * @return the value of sys_attachment.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.updated_by
     *
     * @param updatedBy the value for sys_attachment.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.creation_date
     *
     * @return the value of sys_attachment.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.creation_date
     *
     * @param creationDate the value for sys_attachment.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.created_by
     *
     * @return the value of sys_attachment.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.created_by
     *
     * @param createdBy the value for sys_attachment.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.version
     *
     * @return the value of sys_attachment.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.version
     *
     * @param version the value for sys_attachment.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.content
     *
     * @return the value of sys_attachment.content
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.content
     *
     * @param content the value for sys_attachment.content
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setContent(byte[] content) {
        this.content = content;
    }
}