package com.mybatis.generator.entity.test;

import java.util.Date;

/**
 * Database Table Remarks:
 *   系统配置信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_config_child
 */
public class SysConfigChild {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_child.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_child.param_value
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String paramValue;

    /**
     * Database Column Remarks:
     *   系统参数主表ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_child.parent_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long parentId;

    /**
     * Database Column Remarks:
     *   是否有效 1：有效 0：无效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_child.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Byte validFlag;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_child.remark
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_child.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   更新用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_child.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long updatedBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_child.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date creationDate;

    /**
     * Database Column Remarks:
     *   创建用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_child.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long createdBy;

    /**
     * Database Column Remarks:
     *   版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_child.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer version;

    /**
     * Database Column Remarks:
     *   键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config_child.param_key
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String paramKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_child.id
     *
     * @return the value of sys_config_child.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_child.id
     *
     * @param id the value for sys_config_child.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_child.param_value
     *
     * @return the value of sys_config_child.param_value
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_child.param_value
     *
     * @param paramValue the value for sys_config_child.param_value
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_child.parent_id
     *
     * @return the value of sys_config_child.parent_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_child.parent_id
     *
     * @param parentId the value for sys_config_child.parent_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_child.valid_flag
     *
     * @return the value of sys_config_child.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Byte getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_child.valid_flag
     *
     * @param validFlag the value for sys_config_child.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setValidFlag(Byte validFlag) {
        this.validFlag = validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_child.remark
     *
     * @return the value of sys_config_child.remark
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_child.remark
     *
     * @param remark the value for sys_config_child.remark
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_child.update_date
     *
     * @return the value of sys_config_child.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_child.update_date
     *
     * @param updateDate the value for sys_config_child.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_child.updated_by
     *
     * @return the value of sys_config_child.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_child.updated_by
     *
     * @param updatedBy the value for sys_config_child.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_child.creation_date
     *
     * @return the value of sys_config_child.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_child.creation_date
     *
     * @param creationDate the value for sys_config_child.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_child.created_by
     *
     * @return the value of sys_config_child.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_child.created_by
     *
     * @param createdBy the value for sys_config_child.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_child.version
     *
     * @return the value of sys_config_child.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_child.version
     *
     * @param version the value for sys_config_child.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config_child.param_key
     *
     * @return the value of sys_config_child.param_key
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getParamKey() {
        return paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config_child.param_key
     *
     * @param paramKey the value for sys_config_child.param_key
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setParamKey(String paramKey) {
        this.paramKey = paramKey;
    }
}