package com.mybatis.generator.entity.test;

import java.util.Date;

/**
 * Database Table Remarks:
 *   字典子表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_dict_child
 */
public class SysDictChild {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_child.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   字典表主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_child.sys_dict_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long sysDictId;

    /**
     * Database Column Remarks:
     *   值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_child.dict_value
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String dictValue;

    /**
     * Database Column Remarks:
     *   显示名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_child.display_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String displayName;

    /**
     * Database Column Remarks:
     *   序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_child.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer sequenceNo;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_child.dict_desc
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String dictDesc;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_child.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   更新用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_child.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long updatedBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_child.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date creationDate;

    /**
     * Database Column Remarks:
     *   创建用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_child.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long createdBy;

    /**
     * Database Column Remarks:
     *   版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_child.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer version;

    /**
     * Database Column Remarks:
     *   子表父节点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_child.child_parent_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long childParentId;

    /**
     * Database Column Remarks:
     *   字典表编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_child.sys_dict_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String sysDictCode;

    /**
     * Database Column Remarks:
     *   是否有效 true：有效 false：无效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_child.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Byte validFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_child.id
     *
     * @return the value of sys_dict_child.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_child.id
     *
     * @param id the value for sys_dict_child.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_child.sys_dict_id
     *
     * @return the value of sys_dict_child.sys_dict_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getSysDictId() {
        return sysDictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_child.sys_dict_id
     *
     * @param sysDictId the value for sys_dict_child.sys_dict_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setSysDictId(Long sysDictId) {
        this.sysDictId = sysDictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_child.dict_value
     *
     * @return the value of sys_dict_child.dict_value
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_child.dict_value
     *
     * @param dictValue the value for sys_dict_child.dict_value
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_child.display_name
     *
     * @return the value of sys_dict_child.display_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_child.display_name
     *
     * @param displayName the value for sys_dict_child.display_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_child.sequence_no
     *
     * @return the value of sys_dict_child.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getSequenceNo() {
        return sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_child.sequence_no
     *
     * @param sequenceNo the value for sys_dict_child.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_child.dict_desc
     *
     * @return the value of sys_dict_child.dict_desc
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getDictDesc() {
        return dictDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_child.dict_desc
     *
     * @param dictDesc the value for sys_dict_child.dict_desc
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setDictDesc(String dictDesc) {
        this.dictDesc = dictDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_child.update_date
     *
     * @return the value of sys_dict_child.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_child.update_date
     *
     * @param updateDate the value for sys_dict_child.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_child.updated_by
     *
     * @return the value of sys_dict_child.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_child.updated_by
     *
     * @param updatedBy the value for sys_dict_child.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_child.creation_date
     *
     * @return the value of sys_dict_child.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_child.creation_date
     *
     * @param creationDate the value for sys_dict_child.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_child.created_by
     *
     * @return the value of sys_dict_child.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_child.created_by
     *
     * @param createdBy the value for sys_dict_child.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_child.version
     *
     * @return the value of sys_dict_child.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_child.version
     *
     * @param version the value for sys_dict_child.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_child.child_parent_id
     *
     * @return the value of sys_dict_child.child_parent_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getChildParentId() {
        return childParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_child.child_parent_id
     *
     * @param childParentId the value for sys_dict_child.child_parent_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setChildParentId(Long childParentId) {
        this.childParentId = childParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_child.sys_dict_code
     *
     * @return the value of sys_dict_child.sys_dict_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getSysDictCode() {
        return sysDictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_child.sys_dict_code
     *
     * @param sysDictCode the value for sys_dict_child.sys_dict_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setSysDictCode(String sysDictCode) {
        this.sysDictCode = sysDictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_child.valid_flag
     *
     * @return the value of sys_dict_child.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Byte getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_child.valid_flag
     *
     * @param validFlag the value for sys_dict_child.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setValidFlag(Byte validFlag) {
        this.validFlag = validFlag;
    }
}