package com.mybatis.generator.entity.test;

import java.util.Date;

/**
 * Database Table Remarks:
 *   部门表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_dept
 */
public class SysDept {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   部门编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.dept_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String deptCode;

    /**
     * Database Column Remarks:
     *   部门名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.dept_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String deptName;

    /**
     * Database Column Remarks:
     *   父级部门ID,根部门父级ID为-1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.parent_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long parentId;

    /**
     * Database Column Remarks:
     *   部门级别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.dept_level
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer deptLevel;

    /**
     * Database Column Remarks:
     *   部门全路径，从根部门计算
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.dept_code_path
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String deptCodePath;

    /**
     * Database Column Remarks:
     *   是否有效 1：有效 0：无效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Byte validFlag;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.dept_desc
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String deptDesc;

    /**
     * Database Column Remarks:
     *   序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer sequenceNo;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   更新用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long updatedBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date creationDate;

    /**
     * Database Column Remarks:
     *   创建用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long createdBy;

    /**
     * Database Column Remarks:
     *   版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.id
     *
     * @return the value of sys_dept.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.id
     *
     * @param id the value for sys_dept.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.dept_code
     *
     * @return the value of sys_dept.dept_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.dept_code
     *
     * @param deptCode the value for sys_dept.dept_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.dept_name
     *
     * @return the value of sys_dept.dept_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.dept_name
     *
     * @param deptName the value for sys_dept.dept_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.parent_id
     *
     * @return the value of sys_dept.parent_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.parent_id
     *
     * @param parentId the value for sys_dept.parent_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.dept_level
     *
     * @return the value of sys_dept.dept_level
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getDeptLevel() {
        return deptLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.dept_level
     *
     * @param deptLevel the value for sys_dept.dept_level
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setDeptLevel(Integer deptLevel) {
        this.deptLevel = deptLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.dept_code_path
     *
     * @return the value of sys_dept.dept_code_path
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getDeptCodePath() {
        return deptCodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.dept_code_path
     *
     * @param deptCodePath the value for sys_dept.dept_code_path
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setDeptCodePath(String deptCodePath) {
        this.deptCodePath = deptCodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.valid_flag
     *
     * @return the value of sys_dept.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Byte getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.valid_flag
     *
     * @param validFlag the value for sys_dept.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setValidFlag(Byte validFlag) {
        this.validFlag = validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.dept_desc
     *
     * @return the value of sys_dept.dept_desc
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getDeptDesc() {
        return deptDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.dept_desc
     *
     * @param deptDesc the value for sys_dept.dept_desc
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setDeptDesc(String deptDesc) {
        this.deptDesc = deptDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.sequence_no
     *
     * @return the value of sys_dept.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getSequenceNo() {
        return sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.sequence_no
     *
     * @param sequenceNo the value for sys_dept.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.update_date
     *
     * @return the value of sys_dept.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.update_date
     *
     * @param updateDate the value for sys_dept.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.updated_by
     *
     * @return the value of sys_dept.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.updated_by
     *
     * @param updatedBy the value for sys_dept.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.creation_date
     *
     * @return the value of sys_dept.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.creation_date
     *
     * @param creationDate the value for sys_dept.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.created_by
     *
     * @return the value of sys_dept.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.created_by
     *
     * @param createdBy the value for sys_dept.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.version
     *
     * @return the value of sys_dept.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.version
     *
     * @param version the value for sys_dept.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}