package com.mybatis.generator.entity.test;

import java.util.Date;

/**
 * Database Table Remarks:
 *   群组表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_group
 */
public class SysGroup {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.group_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String groupCode;

    /**
     * Database Column Remarks:
     *   群组名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.group_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String groupName;

    /**
     * Database Column Remarks:
     *   是否有效 1：有效 0：无效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Byte validFlag;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.group_desc
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String groupDesc;

    /**
     * Database Column Remarks:
     *   序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer sequenceNo;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   更新用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long updatedBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date creationDate;

    /**
     * Database Column Remarks:
     *   创建用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long createdBy;

    /**
     * Database Column Remarks:
     *   版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.id
     *
     * @return the value of sys_group.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.id
     *
     * @param id the value for sys_group.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.group_code
     *
     * @return the value of sys_group.group_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.group_code
     *
     * @param groupCode the value for sys_group.group_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.group_name
     *
     * @return the value of sys_group.group_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.group_name
     *
     * @param groupName the value for sys_group.group_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.valid_flag
     *
     * @return the value of sys_group.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Byte getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.valid_flag
     *
     * @param validFlag the value for sys_group.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setValidFlag(Byte validFlag) {
        this.validFlag = validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.group_desc
     *
     * @return the value of sys_group.group_desc
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getGroupDesc() {
        return groupDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.group_desc
     *
     * @param groupDesc the value for sys_group.group_desc
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setGroupDesc(String groupDesc) {
        this.groupDesc = groupDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.sequence_no
     *
     * @return the value of sys_group.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getSequenceNo() {
        return sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.sequence_no
     *
     * @param sequenceNo the value for sys_group.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.update_date
     *
     * @return the value of sys_group.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.update_date
     *
     * @param updateDate the value for sys_group.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.updated_by
     *
     * @return the value of sys_group.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.updated_by
     *
     * @param updatedBy the value for sys_group.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.creation_date
     *
     * @return the value of sys_group.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.creation_date
     *
     * @param creationDate the value for sys_group.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.created_by
     *
     * @return the value of sys_group.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.created_by
     *
     * @param createdBy the value for sys_group.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.version
     *
     * @return the value of sys_group.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.version
     *
     * @param version the value for sys_group.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}