package com.mybatis.generator.entity.test;

import java.util.Date;

/**
 * Database Table Remarks:
 *   群组关系表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_group_relation
 */
public class SysGroupRelationCache {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_relation.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   群组表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_relation.sys_group_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long sysGroupId;

    /**
     * Database Column Remarks:
     *   群组类型 1：用户群组 2：部门群组 3：角色群组 4：岗位群组 5：群组群组
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_relation.group_type
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String groupType;

    /**
     * Database Column Remarks:
     *   用户表主键/角色表主键/群组表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_relation.group_type_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long groupTypeId;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_relation.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   更新用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_relation.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long updatedBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_relation.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date creationDate;

    /**
     * Database Column Remarks:
     *   创建用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_relation.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long createdBy;

    /**
     * Database Column Remarks:
     *   版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_relation.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_relation.id
     *
     * @return the value of sys_group_relation.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_relation.id
     *
     * @param id the value for sys_group_relation.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_relation.sys_group_id
     *
     * @return the value of sys_group_relation.sys_group_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getSysGroupId() {
        return sysGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_relation.sys_group_id
     *
     * @param sysGroupId the value for sys_group_relation.sys_group_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setSysGroupId(Long sysGroupId) {
        this.sysGroupId = sysGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_relation.group_type
     *
     * @return the value of sys_group_relation.group_type
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getGroupType() {
        return groupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_relation.group_type
     *
     * @param groupType the value for sys_group_relation.group_type
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setGroupType(String groupType) {
        this.groupType = groupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_relation.group_type_id
     *
     * @return the value of sys_group_relation.group_type_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getGroupTypeId() {
        return groupTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_relation.group_type_id
     *
     * @param groupTypeId the value for sys_group_relation.group_type_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setGroupTypeId(Long groupTypeId) {
        this.groupTypeId = groupTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_relation.update_date
     *
     * @return the value of sys_group_relation.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_relation.update_date
     *
     * @param updateDate the value for sys_group_relation.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_relation.updated_by
     *
     * @return the value of sys_group_relation.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_relation.updated_by
     *
     * @param updatedBy the value for sys_group_relation.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_relation.creation_date
     *
     * @return the value of sys_group_relation.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_relation.creation_date
     *
     * @param creationDate the value for sys_group_relation.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_relation.created_by
     *
     * @return the value of sys_group_relation.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_relation.created_by
     *
     * @param createdBy the value for sys_group_relation.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_relation.version
     *
     * @return the value of sys_group_relation.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_relation.version
     *
     * @param version the value for sys_group_relation.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}