package com.mybatis.generator.entity.test;

import java.util.Date;

/**
 * Database Table Remarks:
 *   登录日志表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_login_log
 */
public class SysLoginLog {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.title
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String title;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.user_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   日志类型 系统登录、业务操作、系统管理、安全管理、安全审计
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.log_type
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String logType;

    /**
     * Database Column Remarks:
     *   登录日志 退出日志 登录失败日志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.operation
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String operation;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.create_time
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   是否执行成功,1：是 0:否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.succeed
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Byte succeed;

    /**
     * Database Column Remarks:
     *   登录ip
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.op_ip
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String opIp;

    /**
     * Database Column Remarks:
     *   具体消息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.message
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.id
     *
     * @return the value of sys_login_log.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.id
     *
     * @param id the value for sys_login_log.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.title
     *
     * @return the value of sys_login_log.title
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.title
     *
     * @param title the value for sys_login_log.title
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.user_name
     *
     * @return the value of sys_login_log.user_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.user_name
     *
     * @param userName the value for sys_login_log.user_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.log_type
     *
     * @return the value of sys_login_log.log_type
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.log_type
     *
     * @param logType the value for sys_login_log.log_type
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setLogType(String logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.operation
     *
     * @return the value of sys_login_log.operation
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.operation
     *
     * @param operation the value for sys_login_log.operation
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setOperation(String operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.create_time
     *
     * @return the value of sys_login_log.create_time
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.create_time
     *
     * @param createTime the value for sys_login_log.create_time
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.succeed
     *
     * @return the value of sys_login_log.succeed
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Byte getSucceed() {
        return succeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.succeed
     *
     * @param succeed the value for sys_login_log.succeed
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setSucceed(Byte succeed) {
        this.succeed = succeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.op_ip
     *
     * @return the value of sys_login_log.op_ip
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getOpIp() {
        return opIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.op_ip
     *
     * @param opIp the value for sys_login_log.op_ip
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setOpIp(String opIp) {
        this.opIp = opIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.message
     *
     * @return the value of sys_login_log.message
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.message
     *
     * @param message the value for sys_login_log.message
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setMessage(String message) {
        this.message = message;
    }
}