package com.mybatis.generator.entity.test;

import java.util.Date;

/**
 * Database Table Remarks:
 *   菜单权限表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_menu
 */
public class SysMenu {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   父菜单ID，根菜单此值为-1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.parent_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long parentId;

    /**
     * Database Column Remarks:
     *   菜单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String menuCode;

    /**
     * Database Column Remarks:
     *   菜单名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String menuName;

    /**
     * Database Column Remarks:
     *   系统菜单 1：前台 2：后台
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_system
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String menuSystem;

    /**
     * Database Column Remarks:
     *   菜单URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_url
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String menuUrl;

    /**
     * Database Column Remarks:
     *   菜单全路径，从根菜单计算
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_code_path
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String menuCodePath;

    /**
     * Database Column Remarks:
     *   菜单级别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_level
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer menuLevel;

    /**
     * Database Column Remarks:
     *   授权(多个用逗号分隔，如：user:list,user:create)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.perms
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String perms;

    /**
     * Database Column Remarks:
     *   类型 0：目录 1：菜单 2：按钮
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_type
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String menuType;

    /**
     * Database Column Remarks:
     *   菜单图标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_icon
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String menuIcon;

    /**
     * Database Column Remarks:
     *   序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer sequenceNo;

    /**
     * Database Column Remarks:
     *   显示状态 1:显示 0:隐藏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.is_display
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Byte isDisplay;

    /**
     * Database Column Remarks:
     *   菜单状态 1:启用 0:禁用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.status
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   更新用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long updatedBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date creationDate;

    /**
     * Database Column Remarks:
     *   创建用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long createdBy;

    /**
     * Database Column Remarks:
     *   版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.id
     *
     * @return the value of sys_menu.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.id
     *
     * @param id the value for sys_menu.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.parent_id
     *
     * @return the value of sys_menu.parent_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.parent_id
     *
     * @param parentId the value for sys_menu.parent_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_code
     *
     * @return the value of sys_menu.menu_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_code
     *
     * @param menuCode the value for sys_menu.menu_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_name
     *
     * @return the value of sys_menu.menu_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_name
     *
     * @param menuName the value for sys_menu.menu_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_system
     *
     * @return the value of sys_menu.menu_system
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getMenuSystem() {
        return menuSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_system
     *
     * @param menuSystem the value for sys_menu.menu_system
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setMenuSystem(String menuSystem) {
        this.menuSystem = menuSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_url
     *
     * @return the value of sys_menu.menu_url
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_url
     *
     * @param menuUrl the value for sys_menu.menu_url
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_code_path
     *
     * @return the value of sys_menu.menu_code_path
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getMenuCodePath() {
        return menuCodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_code_path
     *
     * @param menuCodePath the value for sys_menu.menu_code_path
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setMenuCodePath(String menuCodePath) {
        this.menuCodePath = menuCodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_level
     *
     * @return the value of sys_menu.menu_level
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getMenuLevel() {
        return menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_level
     *
     * @param menuLevel the value for sys_menu.menu_level
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setMenuLevel(Integer menuLevel) {
        this.menuLevel = menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.perms
     *
     * @return the value of sys_menu.perms
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getPerms() {
        return perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.perms
     *
     * @param perms the value for sys_menu.perms
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setPerms(String perms) {
        this.perms = perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_type
     *
     * @return the value of sys_menu.menu_type
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_type
     *
     * @param menuType the value for sys_menu.menu_type
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_icon
     *
     * @return the value of sys_menu.menu_icon
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_icon
     *
     * @param menuIcon the value for sys_menu.menu_icon
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.sequence_no
     *
     * @return the value of sys_menu.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getSequenceNo() {
        return sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.sequence_no
     *
     * @param sequenceNo the value for sys_menu.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.is_display
     *
     * @return the value of sys_menu.is_display
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Byte getIsDisplay() {
        return isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.is_display
     *
     * @param isDisplay the value for sys_menu.is_display
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setIsDisplay(Byte isDisplay) {
        this.isDisplay = isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.status
     *
     * @return the value of sys_menu.status
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.status
     *
     * @param status the value for sys_menu.status
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.update_date
     *
     * @return the value of sys_menu.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.update_date
     *
     * @param updateDate the value for sys_menu.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.updated_by
     *
     * @return the value of sys_menu.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.updated_by
     *
     * @param updatedBy the value for sys_menu.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.creation_date
     *
     * @return the value of sys_menu.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.creation_date
     *
     * @param creationDate the value for sys_menu.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.created_by
     *
     * @return the value of sys_menu.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.created_by
     *
     * @param createdBy the value for sys_menu.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.version
     *
     * @return the value of sys_menu.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.version
     *
     * @param version the value for sys_menu.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}