package com.mybatis.generator.entity.test;

import java.util.Date;

/**
 * Database Table Remarks:
 *   角色信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role
 */
public class SysRole {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String roleCode;

    /**
     * Database Column Remarks:
     *   角色名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String roleName;

    /**
     * Database Column Remarks:
     *   是否有效 1：有效 0：无效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Byte validFlag;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_desc
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private String roleDesc;

    /**
     * Database Column Remarks:
     *   序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer sequenceNo;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   更新用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long updatedBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date creationDate;

    /**
     * Database Column Remarks:
     *   创建用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long createdBy;

    /**
     * Database Column Remarks:
     *   版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.id
     *
     * @return the value of sys_role.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.id
     *
     * @param id the value for sys_role.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_code
     *
     * @return the value of sys_role.role_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_code
     *
     * @param roleCode the value for sys_role.role_code
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_name
     *
     * @return the value of sys_role.role_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_name
     *
     * @param roleName the value for sys_role.role_name
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.valid_flag
     *
     * @return the value of sys_role.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Byte getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.valid_flag
     *
     * @param validFlag the value for sys_role.valid_flag
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setValidFlag(Byte validFlag) {
        this.validFlag = validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_desc
     *
     * @return the value of sys_role.role_desc
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_desc
     *
     * @param roleDesc the value for sys_role.role_desc
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.sequence_no
     *
     * @return the value of sys_role.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getSequenceNo() {
        return sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.sequence_no
     *
     * @param sequenceNo the value for sys_role.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.update_date
     *
     * @return the value of sys_role.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.update_date
     *
     * @param updateDate the value for sys_role.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.updated_by
     *
     * @return the value of sys_role.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.updated_by
     *
     * @param updatedBy the value for sys_role.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.creation_date
     *
     * @return the value of sys_role.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.creation_date
     *
     * @param creationDate the value for sys_role.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.created_by
     *
     * @return the value of sys_role.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.created_by
     *
     * @param createdBy the value for sys_role.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.version
     *
     * @return the value of sys_role.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.version
     *
     * @param version the value for sys_role.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}