package com.mybatis.generator.entity.test;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户部门岗位关系表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_user_dept_position
 */
public class SysUserDeptPosition {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_dept_position.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_dept_position.user_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   部门ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_dept_position.dept_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long deptId;

    /**
     * Database Column Remarks:
     *   岗位ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_dept_position.position_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long positionId;

    /**
     * Database Column Remarks:
     *   是否主部门，1：是 0：否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_dept_position.chief_dept
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Byte chiefDept;

    /**
     * Database Column Remarks:
     *   序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_dept_position.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer sequenceNo;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_dept_position.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   更新用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_dept_position.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long updatedBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_dept_position.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Date creationDate;

    /**
     * Database Column Remarks:
     *   创建用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_dept_position.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Long createdBy;

    /**
     * Database Column Remarks:
     *   版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_dept_position.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_dept_position.id
     *
     * @return the value of sys_user_dept_position.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_dept_position.id
     *
     * @param id the value for sys_user_dept_position.id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_dept_position.user_id
     *
     * @return the value of sys_user_dept_position.user_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_dept_position.user_id
     *
     * @param userId the value for sys_user_dept_position.user_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_dept_position.dept_id
     *
     * @return the value of sys_user_dept_position.dept_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_dept_position.dept_id
     *
     * @param deptId the value for sys_user_dept_position.dept_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_dept_position.position_id
     *
     * @return the value of sys_user_dept_position.position_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_dept_position.position_id
     *
     * @param positionId the value for sys_user_dept_position.position_id
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setPositionId(Long positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_dept_position.chief_dept
     *
     * @return the value of sys_user_dept_position.chief_dept
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Byte getChiefDept() {
        return chiefDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_dept_position.chief_dept
     *
     * @param chiefDept the value for sys_user_dept_position.chief_dept
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setChiefDept(Byte chiefDept) {
        this.chiefDept = chiefDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_dept_position.sequence_no
     *
     * @return the value of sys_user_dept_position.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getSequenceNo() {
        return sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_dept_position.sequence_no
     *
     * @param sequenceNo the value for sys_user_dept_position.sequence_no
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_dept_position.update_date
     *
     * @return the value of sys_user_dept_position.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_dept_position.update_date
     *
     * @param updateDate the value for sys_user_dept_position.update_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_dept_position.updated_by
     *
     * @return the value of sys_user_dept_position.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_dept_position.updated_by
     *
     * @param updatedBy the value for sys_user_dept_position.updated_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_dept_position.creation_date
     *
     * @return the value of sys_user_dept_position.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_dept_position.creation_date
     *
     * @param creationDate the value for sys_user_dept_position.creation_date
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_dept_position.created_by
     *
     * @return the value of sys_user_dept_position.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_dept_position.created_by
     *
     * @param createdBy the value for sys_user_dept_position.created_by
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_dept_position.version
     *
     * @return the value of sys_user_dept_position.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_dept_position.version
     *
     * @param version the value for sys_user_dept_position.version
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}