package com.mybatis.generator.mapper.test;

import com.mybatis.generator.entity.test.SysConfigChild;
import com.treach.platform.base.BaseMapper;

public interface SysConfigChildMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_child
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_child
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    int insert(SysConfigChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_child
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    int insertSelective(SysConfigChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_child
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    SysConfigChild selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_child
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    int updateByPrimaryKeySelective(SysConfigChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config_child
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    int updateByPrimaryKey(SysConfigChild record);
}