package com.mybatis.generator.mapper.test;

import com.mybatis.generator.entity.test.SysDictChild;
import com.treach.platform.base.BaseMapper;

public interface SysDictChildMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_child
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_child
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    int insert(SysDictChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_child
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    int insertSelective(SysDictChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_child
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    SysDictChild selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_child
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    int updateByPrimaryKeySelective(SysDictChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_child
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    int updateByPrimaryKey(SysDictChild record);
}