package com.mybatis.generator.mapper.test;

import com.mybatis.generator.entity.test.SysPasswordTemplateItem;
import com.treach.platform.base.BaseMapper;

public interface SysPasswordTemplateItemMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_password_template_item
     *
     * @mbg.generated Mon Dec 23 16:39:02 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_password_template_item
     *
     * @mbg.generated Mon Dec 23 16:39:02 CST 2019
     */
    int insert(SysPasswordTemplateItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_password_template_item
     *
     * @mbg.generated Mon Dec 23 16:39:02 CST 2019
     */
    int insertSelective(SysPasswordTemplateItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_password_template_item
     *
     * @mbg.generated Mon Dec 23 16:39:02 CST 2019
     */
    SysPasswordTemplateItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_password_template_item
     *
     * @mbg.generated Mon Dec 23 16:39:02 CST 2019
     */
    int updateByPrimaryKeySelective(SysPasswordTemplateItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_password_template_item
     *
     * @mbg.generated Mon Dec 23 16:39:02 CST 2019
     */
    int updateByPrimaryKey(SysPasswordTemplateItem record);
}