package com.mybatis.generator.mapper.test;

import com.mybatis.generator.entity.test.SysUser;
import com.treach.platform.base.BaseMapper;

public interface SysUserMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Dec 23 16:41:38 CST 2019
     */
    int insertSelective(SysUser record);
}